name: Build DSMF-Decode-Test on MSVC Toolchain (Win2025)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        required: true
        default: "main"

jobs:
  msvc-build:
    runs-on: windows-2025-vs2026
    steps:
      - name: Build DSMF-Decode-Test
        run: |
          chcp 65001
          pushd C:\
          git clone -b ${{ github.event.inputs.branch }} --depth=1 https://github.com/Waim908/DSMF-Decode-Test.git
          cd DSMF-Decode-Test
          .\build.bat

      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DSMF-Decode-Test-EXEs
          path: C:\DSMF-Decode-Test\*.exe
